version: "3.8"

services:

    # Grocery booking API Service
    grocery-booking-api-service:
        container_name: grocery_booking_api
        image: grocery-booking-api-latest
        build:
            context: .
            dockerfile: grocery-booking-api/docker/Dockerfile
        ports:
        - "3000:3000"
        # env_file:
        #     - .env/common.env
        volumes:
        - ./grocery-booking-api/src:/home/user/src
        - ./grocery-booking-api/node_modules:/home/user/node_modules
        - ./grocery-booking-api/tsconfig.json:/home/user/tsconfig.json
        command: npm run start:dev

    # Database to handle grocery_booking API data
    postgres-database:
      container_name: postgres-database
      image: postgres
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: grocery_booking
      ports:
        - "5434:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: